# Generated by Django 4.0.10 on 2023-04-15 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_id',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
