# Generated by Django 4.0.10 on 2023-04-15 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_cagetory_category'),
        ('posts', '0004_alter_post_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
