# Generated by Django 4.0.10 on 2023-04-15 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_comment_updated_at_comment_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
