# Generated by Django 4.0.10 on 2023-04-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activationmodel',
            old_name='address',
            new_name='token',
        ),
    ]
