# Generated by Django 4.0.10 on 2023-04-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_adminuser',
            new_name='is_staff',
        ),
    ]
